import Head from 'next/head'
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Learning Kanas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='py-5'>
        <section>
          <div className='container text-center'>
            <div className='row'>
              <div className='col-md-8 offset-md-2'>
                <h1>仮名</h1>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className='container'>
            <div className='row'>
              <div className='col-md-8 offset-md-2'>
                <p className='fs-4 font-mono'>
                  Welcome to the world of <span className='accent'>Japanese kana</span>! <br/>
                  The kana are a set of symbols used in Japanese writing, consisting of hiragana and katakana. Hiragana is used to write native Japanese words, while katakana is used to write words borrowed from other languages, as well as onomatopoeic words.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className='container'>
            <div className='row'>
              <div className='col-md-8 offset-md-2'>
                <p>
                  Here are some important things to know about the Japanese kana:
                </p>
                <ul>
                  <li>There are a total of 46 basic kana, with 24 hiragana and 22 katakana</li>
                  <li>Each kana represents a specific sound in Japanese</li>
                  <li>The kana are written in a specific order: a-i-u-e-o for vowels, and k-s-t-n-h-m-y-r-w for consonants</li>
                  <li>Hiragana and katakana look similar, but their shapes are slightly different</li>
                  <li>In written Japanese, hiragana is typically used for particles, verb endings, and grammatical constructs, while katakana is used for foreign words and emphasis</li>
                </ul>
                <p>
                  To begin learning the kana, it&apos;s helpful to first learn the basic sounds and their corresponding symbols. Practice writing them out and saying them aloud to help with memorization. With practice and repetition, you&apos;ll be able to read and write Japanese words in no time!
                </p>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className='container'>
            <div className='row py-5'>
              <div className='col-md-1 offset-md-5'>
                <Link href="hiragana-chart">
                  <button type='button' className='btn btn-primary'>Hiragana Chart</button>
                </Link>
              </div>
              <div className='col-md-1'>
                <Link href="katakana-chart">
                  <button type='button' className='btn btn-primary'>Katakana Chart</button>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
