import Head from 'next/head'

export default function StyleGuide() {
  return (
    <>
      <Head>
        <title>Learning Kanas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
            
            <h1 className=''>Title Heading 1</h1>
            <h2 className=''>Title Heading 2</h2>
            <h3 className=''>Title Heading 3</h3>
            <h4 className=''>Title Heading 4</h4>
            
            <p className='py-1'>
              <span>a</span>
              <span>i</span>
              <span>u</span>
              <span>e</span>
              <span>o</span>
            </p>
            <p className='py-1'>
              <span className='font-mono'>a</span>
              <span className='font-mono'>i</span>
              <span className='font-mono'>u</span>
              <span className='font-mono'>e</span>
              <span className='font-mono'>o</span>
            </p>
            <p className='py-1'>
              <span className='font-kana'>あ</span>
              <span className='font-kana'>い</span>
              <span className='font-kana'>う</span>
              <span className='font-kana'>え</span>
              <span className='font-kana'>お</span>
            </p>
            <p className='py-1 intro-text'>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nihil sit unde delectus recusandae illum dolore quod soluta nostrum debitis, eius cumque ad eligendi consequatur laborum placeat aut voluptatem facere?
            </p>
      </main>
    </>
  )
}
